"""add gmail_accounts table

Revision ID: d68cf3aa323b
Revises: eeb7626d7ce3
Create Date: 2026-09-27 23:18:12.982086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68cf3aa323b'
down_revision: Union[str, Sequence[str], None] = 'eeb7626d7ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('google_account_email', sa.String(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('last_history_id', sa.String(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gmail_accounts')
    # ### end Alembic commands ###
